cc_binary(
    name = "map-order-book",
    srcs = ["map_order_book.cpp"],
    deps = ["//lib:map-order-book"]
)

cc_binary(
    name = "spsc-queue",
    srcs = ["spsc_queue.cpp"],
    deps = ["//lib:spsc-queue"]
)
