cc_test(
    name = "linear-probing-hash-set",
    srcs = ["test_linear_probing_hash_set.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//lib:linear-probing-hash-set"
    ]
)

cc_test(
    name = "map-order-book",
    srcs = ["test_map_order_book.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//lib:map-order-book"
    ]
)

cc_test(
    name = "spsc-queue",
    srcs = ["test_spsc_queue.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//lib:spsc-queue"
    ]
)

cc_test(
    name = "vector-order-book",
    srcs = ["test_vector_order_book.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//lib:vector-order-book"
    ]
)

