cc_test(
    name = "spsc-queue",
    srcs = ["spsc_queue.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//lib:spsc-queue"
    ]
)

cc_test(
    name = "map-order-book",
    srcs = ["map_order_book.cpp"],
    deps = [
        "@googletest//:gtest_main",
        "//lib:map-order-book"
    ]
)
